# asset_fields.py

PRIORITY_KEYS = [
    "category",
    "prev_emp",
    "prev_emp_code",
    "prev_given_date",
    "collected_date",
    "area_of_collection",
    "model",
    "system_model",
    "system_manufacturer",
    "hdd",
    "os",
    "storage",
    "main_circuit_board",
    "hdd_type",
    "battery_type",
    "domain",
    "ip_address",
    "processor",
    "ram",
    "imei1",
    "imei2",
    "it_tag",
    "accounts_tag",
    "cpu_asset_tag",
    "IT_tagC",
    "accounts_tagC",
    "serial_no",
    "endpoint_name",
    "IT_tagM",
    "accounts_tagM",
    "mtr_asset_tag",
    "monitor_asset_tag",
    "monitor_make",
    "purchase_date",
    "invoice_no",
    "vendor",
    "license",
    "employee_code",
    "employee_name",
    "given_date",
    "year",
    "area",
    "state",
    "amount",
    "gst_18",
    "gst_22",
    "gst_28",
    "total",
    "send_by",
    "courier_by",
    "received",
    "received_on_approval",
    "status",
    "remarks",
]

#FIELD OWNERSHIP RULES

IMMUTABLE_FIELDS = {
"_id",
"category",
"serial_no",
"imei1",
"asset_tag",
"cpu_asset_tag",
"monitor_asset_tag",
"it_tag",
"IT_tagC",
"IT_tagM",
"accounts_tag",
"accounts_tagC",
"accounts_tagM",
"created_at", # (not created yet)
}

SYSTEM_CONTROLLED_FIELDS = {
"updated_at", # (not created yet)
"remarks", # (append-only)
"total_locked",
}

USER_EDITABLE_FIELDS = {
"prev_emp",
"username", 
"prev_emp_code",
"user_code",
"area_of_collection",
"area",
"state",
"amount",
"gst_18",
"gst_22",
"gst_28",
"total",
"purchase_date",
"prev_given_date",
"given_date",
"collected_date",
"year",
"status",
"remarks",
"invoice_no",
"vendor",
"license",
"os",
"model",
"system_manufacturer",
"domain",
"ip_address",
"processor",
"ram",
"courier_by",
"hdd",
"endpoint_name",
"received_on_approval",
"storage",
"imei2",
"employee_code",
"employee_name",
"send_by",
"system_model",
"received",
"main_circuit_board",
"monitor_make",
"hdd_type",
"battery_type",
}

REMARKS_TRIGGER_FIELDS = {
"status",
"employee_code",
"employee_name",
"area",
"given_date",
}